version: '3' # رقم النسخة بتاعة ترتيب الملف عشان البرنامج يفهم الأوامر صح 

services: # هنا بنبدأ نعرف الخدمات أو البرامج اللي السيستم هيشغلها 
  zeinaguard: # ده الاسم اللي سمينا بيه الخدمة بتاعتنا اللي شايلة مشروع الحماية 
    build: . # بنقول للبرنامج يبني نفسه من الملفات اللي موجودة معاه في نفس المجلد 
    ports: ["5000:5000"] # بنربط منفذ الجهاز بمنفذ البرنامج عشان نعرف نفتح لوحة التحكم من المتصفح 
    volumes: ["./data:/app/data"] # بنربط مجلد البيانات اللي بره بالمجلد اللي جوه عشان المعلومات متضيعش 
    restart: always # بنخلي البرنامج يقوم لوحده فوراً لو حصلت أي مشكلة أو الجهاز أعاد التشغيل